declare const COUNT_DOWN_DATE: number;
declare const COUNT_DOWN_INTERVAL = 1000;
declare const HOURS_IN_DAY = 24;
declare const MINUTES_IN_HOUR = 60;
declare const SECONDS_IN_MINUTE = 60;
declare const MILLIS_IN_SECOND = 1000;
declare const MILLIS_IN_DAY: number;
declare const MILLIS_IN_HOUR: number;
declare const MILLIS_IN_MINUTE: number;
declare const daysEl: HTMLElement;
declare const hoursEl: HTMLElement;
declare const minutesEl: HTMLElement;
declare const secondsEl: HTMLElement;
declare const runCountdownTimer: () => void;
